### ISSUE TITLE
property 'accessConfigs' of class InstanceTemplateNetworkInterfaceProperty should not be mandatory.

### ISSUE THREAD

**Issue by valeriucraciun** [victortrac/stratosphere#6]
property 'accessConfigs' of class InstanceTemplateNetworkInterfaceProperty should not be mandatory.

For instances in private subnet the access is done via a NAT instance and don't need other access.

Google Doc:
networkInterfaces[].accessConfigs[] list    An array of configurations for this interface. Only one access config, ONE_TO_ONE_NAT, is supported per instance. If there are no accessConfigs specified, then this instance will have no external internet access.

BTW ... where did you get from the attributes carnality?

**Comment by victortrac** [comment]
Oops, you're right.

Attributes are done mostly by reading the reference documentation as I build templates that I need. Unfortunately, the documentation is not always clear about required params, so some of it is by trial and error. I haven't really found a reliable, programmatic way to discover the attributes.
